language: node_js
node_js:
  - 14
  - lts/*

# Install gnv with `npm i -g`, then add peer deps with `gnv get-peer-deps`.
install:
  - npm i -g --silent gnv@latest
  - gnv get-peer-deps gnv web-widgets

# Build the gnv template with `gnv build`.
script:
  - gnv build